### ISSUE TITLE
Interpreting results

### ISSUE THREAD

**Issue by kirbyfrugia** [misterblack1/appleII_deadtest#2]
Submitting this as a question, not an issue since I'm sure it's related to my machine or setup. The output from the tool looks a bit off in addition to the error I'm seeing, so I'm not quite sure how to interpret the results.

The test runs fine for several iterations and then I see a bunch of errors all at once. I suspect this means it's not a single DRAM chip that's at fault in this case, but I'm not sure where to start since it looks like it's possibly multiple rows that fail at the same time. However, I'm not certain of that since the data looks corrupted per my notes below.

Setup:

- Apple II Europlus
- Two rows of DRAM installed in the machine
- The diagnostic ROM is installed in one of these: https://www.blue-print.be/product-manuals/Manual-apple-ii-rom-replacement.pdf
- This machine had a lot of oxidation and lots of problems, so there could be multiple faults.

Observations:

- The column headers appear corrupted
- The row headers in one of the images appear corrupted
- Some of the cell data shows up in weird places (i.e. not aligned to column and row headings)
![IMG_5067](https://github.com/misterblack1/appleII_deadtest/assets/4615093/5b3b4fcf-f2fc-40ae-86c2-5c7e2679be30)
![IMG_5068](https://github.com/misterblack1/appleII_deadtest/assets/4615093/05df32b1-8f09-4f92-9eb9-f761600f3b4a)

**Comment by ki3v** [comment]
Hello!  That's a clever looking ROM board.  I like that you can use the jumper to switch between two ROM sets.

Those results do look odd.  I'm guessing here, but I suspect that what's happening is that you have you have chips that are working fine until they warm up, then glitch out.  I'm not sure whether it's RAM chips or address decoding.

I suspect that the reason the data is showing up in odd places on the screen would be because the errors are affecting the zero page (but again, only after the machine has been on a while).  If you reset the machine after the errors begin to show up, does the diagnostic ever report zero page errors?

Do the errors always show up in the _8 through _B rows, or do they sometimes show up elsewhere?  I see it's also curious that in the images it looks like the errors are also in pages with even upper nibbles (0_, 2_, 4_, 6_).  Intuitively that suggests to me that it might be address logic, but again that's just a first guess.

Ignoring the corrupted display, the numbers in the result grid imply bad RAM chips in locations C6 and D6.  But the other oddness, including the screen corruption and the fact that similar adjacent pages have errors in both the first and second banks (implying that the chips in C6 and D6 have the same failure symptoms) seem to suggest that might be a false indicator, and again, that the problem might be in the address decoding logic.  

Or, I suppose, it could be a trace on the motherboard or a socket that is damaged or corroded (maybe it's resulting in a high resistance or noise that gets worse as the temperature rises).

I'm not the hardware expert, but the first thing I'd probably try is to swap C7 with either C5 or C7, and see if the symptoms change.  For instance, if pages 08-0B and 28-2B start showing error 10 or 04, depending on whether you swapped with C5 or C7, then that suggests that the chip that was in C6 really is bad.  C6 also contains bit D4 3 of the first bank, which includes the zero page, so it's theoretically possible that replacing it could also fix the screen corruption and other oddness.

The ROM should work even if you only have 16K of RAM, so if you only have 16 RAM ICs, you could steal an IC from the second bank to replace C6.  If you are able to get the test to run without screen corruption even after running for a long time by replacing C6 with a good chip from row D, then that would be evidence that C6 was causing all of your problems and that the address decoding logic is actually fine.  Then you'd just need to find enough good RAM chips to get row D to all test good.  I hope that's what happens, but to disclaim for the third time I'm basically guessing.

Good luck and please let us know what you try next and how it goes.

**Comment by ki3v** [comment]
Closing as no response received.
