### ISSUE TITLE
ZP RP DDR 00000000

### ISSUE THREAD

**Issue by vibr77** [misterblack1/appleII_deadtest#3]
Hello, 
I am trying to relive an Apple II, I have tested all the RAM and changed number of bad IC but still the A2 is not booting, 
I tried this RAM test rom but I have on a screen a blinking message ZP RP DDR 0000000 with an intermittent bip 

What does that mean ? It may be part of the mystery I try to fix

thanks 

Vincent

**Comment by ki3v** [comment]
Are you sure it isn’t `ZP/SP ERR` instead of `ZP RP DDR`?  And are you sure it prints out all zeros?

The code should print `ZP/SP ERROR (zero page or stack page error) if it finds an error in the first 512 bytes of RAM, and stop there.  Because of the 6502’s special reliance on the first two 256-byte pages of RAM, we can’t run the full test in this case. The numbers should tell you which chips in the first bank of DRAM are causing the problem. 

If it really is saying `00000000` (8 zeros, no ones), then there could be a reporting bug that I can look into.  I don’t recall there being a case where a zero page error should be shown, but the bits to report are all zeros. 

That said, I wonder if the least significant bit is bad in the first bank and stuck at zero, it could change the S to an R, the E to a D, and the 1 to a 0 on the screen.  Those are all a change by subtracting one. That could change `ZP/SP ERR 00000001` into `ZP.RP DRR 00000000`.  So, I’d check the chip for data bit 0 in the first DRAM bank.

**Comment by vibr77** [comment]
I am 100% sure it is DDR, I found out that the 2 8T28 chip were dead and explaining the issue I was facing. 
Vincent

**Comment by ki3v** [comment]
I can imagine the ROM printing `ZP.RP DRR` (one `D`, two `R`s) in the presence of RAM or address chip issues, but `ZP.RP DDR` (two `D`s, one `R`) doesn't make sense to me, because that would change not just the bit but the sequence of bytes written to display RAM.  Did you happen to take a photo?

In any case, I'm glad you found the source of the problem.
